version: "2"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.38
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: sudsandbuds
    ports:
      - 3307:3306
    volumes:
      - ./DB_DUMP/:/docker-entrypoint-initdb.d/
    networks:
      springboot-mysql-net:

  blog-assignment:
    container_name: blog-assignment
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/blog
      - spring.datasource.username=mysql
      - spring.datasource.password=mysql
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: